<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUxmczod\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUxmczod/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUxmczod.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUxmczod\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerUxmczod\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Uxmczod',
    'container.build_id' => '5bb42328',
    'container.build_time' => 1529603913,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUxmczod');
